SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [samurai].[Samurai](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](255) NOT NULL,
	[BattleId] [int] NULL,
 CONSTRAINT [PK_Samurai] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [samurai].[Battle](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](255) NOT NULL,
	[StartDate] [datetime] NULL,
	[EndDateDate] [datetime] NULL,
 CONSTRAINT [PK_Battle] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [samurai].[Quote](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Text] [varchar](255) NOT NULL,
	[SamuraiId] [int] NULL,
 CONSTRAINT [PK_Quote] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [samurai].[Samurai]  WITH CHECK ADD  CONSTRAINT [FK_Samurai_Battle] FOREIGN KEY([BattleId])
REFERENCES [samurai].[Battle] ([Id])
GO

ALTER TABLE [samurai].[Samurai] CHECK CONSTRAINT [FK_Samurai_Battle]
GO

ALTER TABLE [samurai].[Quote]  WITH CHECK ADD  CONSTRAINT [FK_Quote_Samurai] FOREIGN KEY([SamuraiId])
REFERENCES [samurai].[Samurai] ([Id])
GO

ALTER TABLE [samurai].[Quote] CHECK CONSTRAINT [FK_Quote_Samurai]
GO

